### ISSUE TITLE
there was an error creating the child process for this terminal

### ISSUE THREAD

**Issue by marozsas** [Hoaper/ulauncher-zh0per#3]
I've tried to execute a simple command as "_ ls -la" and got a terminal window with a large area on top (and buttons Preferences and Relaunch) saying:
```
there was an error creating the child process for this terminal
Failed to execute child process "-c": Failed to execve: No such file or directory
```
The same message on console/terminal where I've stared "ulauncher".

**Comment by marozsas** [comment]
never mind, is mandatory to set "Environment type" to bash to get it working.

**Comment by marozsas** [comment]
never mind, is mandatory to set "Environment type" to bash to get it working.

**Comment by Hoaper** [comment]
Thanks for report
